### ISSUE TITLE
Insight into the syntax

### ISSUE THREAD

**Issue by JS-E** [deanheard/colo#2]
Hey i've been looking for something like this for a while as i wanted to make my own. 

Could you potentially share how the syntax works for sending commands to it? Like if i could make a packet to change the colour red, how would that look if i was sending that using a command line tool? I'm trying to run this program but i want to simplify it

**Comment by deanheard** [comment]
To use colo, you'd run:
`colo -a <IPADDRESS> -c:red`

If you want to do it yourself, look in CololightController.SetColour and SendMessage for an example. You'd need to convert the following string to a byte array and then send it as a UDP Packet:
535a3030000000000023000000000000000000000000000000000100000000000000000004010602ff00FF0000
